### ISSUE TITLE
I have copied the flink prometheus jar on to EMR Master node; modified the flink-conf.yaml file

### ISSUE THREAD

**Issue by Baludocker** [mbode/flink-prometheus-example#11]
I have copied the flink prometheus jar on to EMR Master node; Included below entries in the flink-conf.yaml file.

metrics.reporters: prom
metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
metrics.reporter.prom.port: 9249

After adding the entries I have started yarn-session; but still I couldnt find the metrics on http://master-node-ip:9249

Where can I find the errors related to this .

**Comment by mbode** [comment]
Hi @Baludocker!

Have you tried all the steps proposed [here](https://stackoverflow.com/questions/55026568/how-to-monitor-apache-flink-in-aws-emr-elasticmapreduce/56504796) (namely providing jar on master as well as slaves, restarting the Flink cluster)? If so, I would advise beginning with looking at JobManager logs. If no errors can be found and the `PrometheusReporter` seems to have started successfully but you still cannot access said port, it might be due to a network misconfiguration. Double-check the [relevant security groups](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-man-sec-groups.html).

**Comment by Baludocker** [comment]
Hi,

I have placed the jar file on the Master Node; and restarted flink cluster after placing the jar file. Right now we are running the setup as below.

Yarn-Session cluster runs on Master node; 
After initialising the Yarn-Session cluster, I have ran the flink job with Job-Manager on Core node; Job Manager will distribute the tasks to Task-Manager;

I can only see the metrics on Core Node at 9249 port as below:

http://<core-node-ip>:9249/metrics

On the above endpoint on Core Node I can only see metrics related to JVM memory; How can I get metrics related to jobs and all..

**Comment by mbode** [comment]
The JobManager only has access to some of the metrics. All task-specific metrics will only be available on TaskManagers. If you are running TaskManagers and the JobManager colocated on a single node, you will need to set a port range, otherwise the TaskManager `PrometheusReporter` instance will not be able to listen. Compare from the [documentation](https://ci.apache.org/projects/flink/flink-docs-stable/monitoring/metrics.html#prometheus-orgapacheflinkmetricsprometheusprometheusreporter): 
> port - (optional) the port the Prometheus exporter listens on, defaults to 9249. In order to be able to run several instances of the reporter on one host (e.g. when one TaskManager is colocated with the JobManager) it is advisable to use a port range like 9250-9260.

**Comment by Baludocker** [comment]
Basically we do have Master Core and Task Managers running on different nodes; when I specify port range in flink-conf.yaml I couldn’t even see metrics from Core Node; Metrics are not available from any endpoint(Be it Master/Core/Task Manager).

Thanks,

Bala
