### ISSUE TITLE
the submit job seems not working

### ISSUE THREAD

**Issue by shenghuatang** [mbode/flink-prometheus-example#13]
![image](https://user-images.githubusercontent.com/6282536/109360593-82fb6980-7855-11eb-8579-37b36c6def67.png)

**Comment by mbode** [comment]
I _assume_ this was due to the semi-random docker-compose project name set by [gradle-docker-compose-plugin](https://github.com/avast/gradle-docker-compose-plugin). I have [disabled](https://github.com/mbode/flink-prometheus-example/commit/2e52579d47e3c0418ac9f38a25d82a3d8b0d7fe9#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06R50) this behaviour now and could not reproduce the error since then. Please reopen in case you still see this error @shenghuatang.
